---
- name: "Upload Ironic image to Cloud Files"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure pyrax is installed
      pip:
        name: pyrax
    - name: "Create container if required"
      local_action:
        module: rax_files
        api_key: "{{ lookup('env', 'RACKSPACE_API_TOKEN') }}"
        username: "{{ lookup('env', 'RACKSPACE_USERNAME') }}"
        region: "{{ lookup('env', 'RACKSPACE_REGION') }}"
        container: "Cody-Test-Ironic-Images"
        state: present
    - name: "Upload Ironic image"
      local_action:
        module: rax_files_objects
        api_key: "{{ lookup('env', 'RACKSPACE_API_TOKEN') }}"
        username: "{{ lookup('env', 'RACKSPACE_USERNAME') }}"
        region: "{{ lookup('env', 'RACKSPACE_REGION') }}"
        tenant_id: "{{ lookup('env', 'RACKSPACE_TENANT_ID') }}"
        container: "Cody-Test-Ironic-Images"
        src: "{{ source_image }}"
        dest: "{{ dest_path }}/{{ ansible_date_time.date }}/{{ dest_file }}-{{ ansible_date_time.date }}.qcow2"
        method: put
    - name: "Update headers"
      debug:
        msg: "TODO"
